//! Minimal C backend — path toward native / self-host.
//! Emits a standalone C99 program for a subset of Kenga IR (main + println/ints).

use crate::ast::{Expr, Item, Program, Stmt};
use crate::error::{KengaError, Result};

pub fn emit_c(program: &Program) -> Result<String> {
    let mut fns = String::new();
    let mut has_main = false;

    for item in &program.items {
        match item {
            Item::Function(f) => {
                if f.name == "main" {
                    has_main = true;
                }
                fns.push_str(&emit_function(f)?);
                fns.push('\n');
            }
            Item::Struct(_) | Item::Intrinsic(_) | Item::EventHandler(_) => {
                // skipped in MVP C emit
            }
        }
    }

    if !has_main {
        return Err(KengaError::new("emit-c requires fn main()", None));
    }

    let mut out = String::new();
    out.push_str("/* Generated by Kenga emit-c - bootstrap native backend */\n");
    out.push_str("#include <stdio.h>\n#include <stdint.h>\n\n");
    out.push_str("static void kenga_println_i64(int64_t v) { printf(\"%lld\\n\", (long long)v); }\n");
    out.push_str("static void kenga_println_str(const char* s) { puts(s); }\n\n");
    out.push_str(&fns);
    Ok(out)
}

fn emit_function(f: &crate::ast::Function) -> Result<String> {
    let ret = match f.ret {
        crate::ast::Type::I64 => "int64_t",
        crate::ast::Type::Void => "void",
        _ => "int64_t",
    };
    let mut s = format!("{ret} {}(", c_ident(&f.name));
    if f.params.is_empty() {
        s.push_str("void");
    } else {
        for (i, p) in f.params.iter().enumerate() {
            if i > 0 {
                s.push_str(", ");
            }
            s.push_str("int64_t ");
            s.push_str(&c_ident(&p.name));
        }
    }
    s.push_str(") {\n");
    for stmt in &f.body.stmts {
        s.push_str(&emit_stmt(stmt, 1)?);
    }
    if matches!(f.ret, crate::ast::Type::I64) && !f.body.stmts.iter().any(|st| matches!(st, Stmt::Return { .. })) {
        s.push_str("  return 0;\n");
    }
    s.push_str("}\n");
    Ok(s)
}

fn emit_stmt(stmt: &Stmt, indent: usize) -> Result<String> {
    let pad = "  ".repeat(indent);
    match stmt {
        Stmt::Let { name, value, .. } => Ok(format!(
            "{pad}int64_t {} = {};\n",
            c_ident(name),
            emit_expr(value)?
        )),
        Stmt::Assign {
            target: crate::ast::AssignTarget::Name(name),
            value,
            ..
        } => Ok(format!(
            "{pad}{} = {};\n",
            c_ident(name),
            emit_expr(value)?
        )),
        Stmt::Expr { expr, .. } => {
            if let Expr::Call { callee, args, .. } = expr {
                if callee == "println" && args.len() == 1 {
                    return match &args[0] {
                        Expr::Str(s, _) => Ok(format!(
                            "{pad}kenga_println_str(\"{}\");\n",
                            escape_c(s)
                        )),
                        other => Ok(format!(
                            "{pad}kenga_println_i64({});\n",
                            emit_expr(other)?
                        )),
                    };
                }
            }
            Ok(format!("{pad}{};\n", emit_expr(expr)?))
        }
        Stmt::Return { value, .. } => match value {
            Some(e) => Ok(format!("{pad}return {};\n", emit_expr(e)?)),
            None => Ok(format!("{pad}return;\n")),
        },
        Stmt::If {
            cond,
            then_block,
            else_block,
            ..
        } => {
            let mut s = format!("{pad}if ({}) {{\n", emit_expr(cond)?);
            for st in &then_block.stmts {
                s.push_str(&emit_stmt(st, indent + 1)?);
            }
            s.push_str(&format!("{pad}}}"));
            if let Some(eb) = else_block {
                s.push_str(" else {\n");
                for st in &eb.stmts {
                    s.push_str(&emit_stmt(st, indent + 1)?);
                }
                s.push_str(&format!("{pad}}}\n"));
            } else {
                s.push('\n');
            }
            Ok(s)
        }
        Stmt::While { cond, body, .. } => {
            let mut s = format!("{pad}while ({}) {{\n", emit_expr(cond)?);
            for st in &body.stmts {
                s.push_str(&emit_stmt(st, indent + 1)?);
            }
            s.push_str(&format!("{pad}}}\n"));
            Ok(s)
        }
        other => Err(KengaError::new(
            format!("emit-c: unsupported statement in MVP ({other:?})"),
            None,
        )),
    }
}

fn emit_expr(expr: &Expr) -> Result<String> {
    match expr {
        Expr::Int(n, _) => Ok(n.to_string()),
        Expr::Bool(true, _) => Ok("1".into()),
        Expr::Bool(false, _) => Ok("0".into()),
        Expr::Ident(name, _) => Ok(c_ident(name)),
        Expr::Unary {
            op: crate::ast::UnaryOp::Neg,
            expr,
            ..
        } => Ok(format!("(-{})", emit_expr(expr)?)),
        Expr::Unary {
            op: crate::ast::UnaryOp::Not,
            expr,
            ..
        } => Ok(format!("(!{})", emit_expr(expr)?)),
        Expr::Binary {
            op, left, right, ..
        } => {
            let o = match op {
                crate::ast::BinaryOp::Add => "+",
                crate::ast::BinaryOp::Sub => "-",
                crate::ast::BinaryOp::Mul => "*",
                crate::ast::BinaryOp::Div => "/",
                crate::ast::BinaryOp::Rem => "%",
                crate::ast::BinaryOp::Eq => "==",
                crate::ast::BinaryOp::Ne => "!=",
                crate::ast::BinaryOp::Lt => "<",
                crate::ast::BinaryOp::Le => "<=",
                crate::ast::BinaryOp::Gt => ">",
                crate::ast::BinaryOp::Ge => ">=",
                crate::ast::BinaryOp::And => "&&",
                crate::ast::BinaryOp::Or => "||",
            };
            Ok(format!("({} {} {})", emit_expr(left)?, o, emit_expr(right)?))
        }
        Expr::Call { callee, args, .. } if callee == "println" => {
            // handled at stmt level
            Err(KengaError::new("println must be a statement for emit-c", None))
        }
        Expr::Str(s, _) => Ok(format!("\"{}\"", escape_c(s))),
        _ => Err(KengaError::new(
            "emit-c: unsupported expression in MVP",
            None,
        )),
    }
}

fn c_ident(name: &str) -> String {
    if name == "main" {
        return "main".into();
    }
    format!("k_{name}")
}

fn escape_c(s: &str) -> String {
    s.replace('\\', "\\\\").replace('"', "\\\"")
}
